# ============================================================
# alerthub-backend — mps-tooling-mdn overrides (DR / Warm-Standby)
# ============================================================

global:
  storageClass: tooling-mdn-netapp-default
  namespace: alert-engine

backend:
  replicas: 1
  appBaseUrl: https://alerthub-sre-mdn.k.example.com
  oauthCallbackUrl: https://alerthub-sre-mdn.k.example.com/api/v1/auth
  netappClusters: '[{"cluster":"100.67.87.8","name":"netapp-mdn-cluster001","region":"mdn"},{"cluster":"100.67.60.23","name":"netapp-rno-cluster001","region":"rno"}]'

build:
  enabled: false

whisper:
  enabled: true
