apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alerthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: graph-database
    app: neo4j
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
