// Package rca — PostgreSQL-backed correlation rule engine.
//
// Adapts RCA-Operator's CRD-driven rule engine for KubeSense's PostgreSQL stack.
// Rules are stored in kubesense_correlation_rules and loaded into memory every 30s.
// Evaluation is O(rules × buffer_entries) per incoming event — acceptable at this scale.
package rca

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"time"
)

// ─── Rule data model ──────────────────────────────────────────────────────────

// RuleCondition is one AND-condition that must match for the rule to fire.
type RuleCondition struct {
	EventType string          `json:"event_type"`           // required
	Scope     string          `json:"scope"`                // samePod|sameNode|sameNamespace|any
	Negate    bool            `json:"negate,omitempty"`
	Attribute *AttributeMatch `json:"attribute,omitempty"`  // optional attribute predicate
}

// AttributeMatch evaluates a key-value attribute on an event.
type AttributeMatch struct {
	Key   string `json:"key"`
	Op    string `json:"op"`   // Equals|NotEquals|Contains|NotContains|Regex|Exists|NotExists|Gte|Lte|Gt|Lt
	Value string `json:"value,omitempty"`
}

// CorrelationRule is the in-memory representation of a kubesense_correlation_rules row.
type CorrelationRule struct {
	ID            string
	Name          string
	Priority      int
	TriggerType   string
	Conditions    []RuleCondition
	IncidentType  string
	Severity      string
	Summary       string         // Go text/template: {{.PodName}}, {{.Namespace}}, {{.NodeName}}, {{.EventType}}
	Scope         string
	AutoGenerated bool
	// Compiled at load time
	tmpl *template.Template
	compiledConds []compiledCondition
}

type compiledCondition struct {
	eventType string
	scope     string
	negate    bool
	attr      *compiledAttr
}

type compiledAttr struct {
	key    string
	op     string
	value  string
	number float64
	regex  *regexp.Regexp
}

// ─── Rule engine ──────────────────────────────────────────────────────────────

// CorrelationResult is returned when a rule fires.
type CorrelationResult struct {
	Fired        bool
	IncidentType string
	Severity     string
	Summary      string
	RuleName     string
	Scope        string
}

// RuleEngine loads rules from PostgreSQL and evaluates them against the buffer.
type RuleEngine struct {
	db      *sql.DB
	buf     *Buffer
	mu      sync.RWMutex
	rules   []*CorrelationRule
	loadedAt time.Time
	reload  time.Duration
}

// NewRuleEngine creates a rule engine backed by the given DB and buffer.
// reload is how often rules are refreshed from the DB (default 30s).
func NewRuleEngine(db *sql.DB, buf *Buffer, reload time.Duration) *RuleEngine {
	if reload <= 0 {
		reload = 30 * time.Second
	}
	return &RuleEngine{db: db, buf: buf, reload: reload}
}

// LoadRules fetches and compiles all rules from the DB.
// Safe to call concurrently — uses write lock.
func (e *RuleEngine) LoadRules(ctx context.Context) error {
	if e.db == nil {
		return nil
	}
	rows, err := e.db.QueryContext(ctx, `
		SELECT id, name, priority, trigger_event_type, conditions,
		       fires_incident_type, fires_severity, fires_summary, scope, auto_generated
		FROM kubesense_correlation_rules
		WHERE (expires_at IS NULL OR expires_at > NOW())
		ORDER BY priority DESC, name ASC
	`)
	if err != nil {
		return fmt.Errorf("loading rules: %w", err)
	}
	defer rows.Close()

	var loaded []*CorrelationRule
	for rows.Next() {
		var r CorrelationRule
		var condJSON []byte
		if err := rows.Scan(&r.ID, &r.Name, &r.Priority, &r.TriggerType, &condJSON,
			&r.IncidentType, &r.Severity, &r.Summary, &r.Scope, &r.AutoGenerated); err != nil {
			continue
		}
		if err := json.Unmarshal(condJSON, &r.Conditions); err != nil {
			continue
		}
		tmpl, err := template.New(r.Name).Parse(r.Summary)
		if err != nil {
			continue
		}
		r.tmpl = tmpl
		r.compiledConds = compileConditions(r.Conditions)
		loaded = append(loaded, &r)
	}

	// Sort: higher priority first, then alphabetically
	sort.SliceStable(loaded, func(i, j int) bool {
		if loaded[i].Priority == loaded[j].Priority {
			return loaded[i].Name < loaded[j].Name
		}
		return loaded[i].Priority > loaded[j].Priority
	})

	e.mu.Lock()
	e.rules = loaded
	e.loadedAt = time.Now()
	e.mu.Unlock()
	return nil
}

// EnsureLoaded reloads rules if the reload interval has passed.
func (e *RuleEngine) EnsureLoaded(ctx context.Context) {
	e.mu.RLock()
	stale := time.Since(e.loadedAt) > e.reload
	e.mu.RUnlock()
	if stale {
		_ = e.LoadRules(ctx)
	}
}

// Evaluate checks all loaded rules against the trigger event.
// Returns the first matching rule's result (highest priority wins).
func (e *RuleEngine) Evaluate(trigger BufferEntry) CorrelationResult {
	e.mu.RLock()
	rules := e.rules
	e.mu.RUnlock()

	entries := e.buf.Snapshot()

	for _, rule := range rules {
		if rule.TriggerType != trigger.EventType {
			continue
		}
		if conditionsMet(trigger, rule.compiledConds, entries) {
			summary := renderSummary(rule.tmpl, trigger)
			return CorrelationResult{
				Fired:        true,
				IncidentType: rule.IncidentType,
				Severity:     rule.Severity,
				Summary:      summary,
				RuleName:     rule.Name,
				Scope:        rule.Scope,
			}
		}
	}
	return CorrelationResult{}
}

// RuleCount returns how many rules are currently loaded.
func (e *RuleEngine) RuleCount() int {
	e.mu.RLock()
	defer e.mu.RUnlock()
	return len(e.rules)
}

// ─── Condition evaluation ─────────────────────────────────────────────────────

func conditionsMet(trigger BufferEntry, conditions []compiledCondition, entries []BufferEntry) bool {
	for _, cond := range conditions {
		found := false
		for _, e := range entries {
			if e.EventType != cond.eventType {
				continue
			}
			if !ScopeMatches(trigger, e, cond.scope) {
				continue
			}
			found = true
			break
		}
		if cond.negate {
			if found {
				return false
			}
		} else if !found {
			return false
		}
	}
	return true
}

func compileConditions(conditions []RuleCondition) []compiledCondition {
	out := make([]compiledCondition, 0, len(conditions))
	for _, c := range conditions {
		scope := c.Scope
		if scope == "" {
			scope = "samePod"
		}
		cc := compiledCondition{
			eventType: c.EventType,
			scope:     scope,
			negate:    c.Negate,
		}
		if c.Attribute != nil {
			cc.attr = compileAttr(c.Attribute)
		}
		out = append(out, cc)
	}
	return out
}

func compileAttr(a *AttributeMatch) *compiledAttr {
	ca := &compiledAttr{key: a.Key, op: a.Op, value: a.Value}
	if a.Op == "Regex" {
		ca.regex, _ = regexp.Compile(a.Value)
	}
	if a.Op == "Gte" || a.Op == "Lte" || a.Op == "Gt" || a.Op == "Lt" {
		ca.number, _ = strconv.ParseFloat(a.Value, 64)
	}
	return ca
}

// ─── Template rendering ───────────────────────────────────────────────────────

type summaryCtx struct {
	PodName   string
	Namespace string
	NodeName  string
	EventType string
	Kind      string
	Name      string
}

func renderSummary(tmpl *template.Template, ev BufferEntry) string {
	if tmpl == nil {
		return ev.EventType + " on " + ev.Scope.Namespace + "/" + ev.Scope.ResourceName
	}
	ctx := summaryCtx{
		PodName:   ev.Scope.PodName,
		Namespace: ev.Scope.Namespace,
		NodeName:  ev.Scope.NodeName,
		EventType: ev.EventType,
		Kind:      ev.Scope.ResourceKind,
		Name:      ev.Scope.ResourceName,
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ctx); err != nil {
		return ev.EventType
	}
	return buf.String()
}

// ─── PostgreSQL schema ────────────────────────────────────────────────────────

// EnsureRuleSchema creates the correlation rules table if it doesn't exist.
func EnsureRuleSchema(ctx context.Context, db *sql.DB) error {
	_, err := db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS kubesense_correlation_rules (
			id                 VARCHAR(64)  PRIMARY KEY DEFAULT gen_random_uuid()::text,
			name               VARCHAR(255) NOT NULL UNIQUE,
			priority           INTEGER      NOT NULL DEFAULT 100,
			trigger_event_type VARCHAR(100) NOT NULL,
			conditions         JSONB        NOT NULL DEFAULT '[]',
			fires_incident_type VARCHAR(100) NOT NULL,
			fires_severity     VARCHAR(10)  NOT NULL,
			fires_summary      TEXT         NOT NULL,
			scope              VARCHAR(20)  NOT NULL DEFAULT 'samePod',
			auto_generated     BOOLEAN      NOT NULL DEFAULT FALSE,
			data_points        INTEGER      NOT NULL DEFAULT 0,
			first_seen         TIMESTAMPTZ,
			last_seen          TIMESTAMPTZ,
			expires_at         TIMESTAMPTZ,
			created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
			updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
		);
		CREATE INDEX IF NOT EXISTS idx_ks_cr_trigger ON kubesense_correlation_rules(trigger_event_type);
		CREATE INDEX IF NOT EXISTS idx_ks_cr_auto     ON kubesense_correlation_rules(auto_generated) WHERE auto_generated = TRUE;
	`)
	if err != nil {
		return err
	}
	// Seed built-in high-value rules on first run
	return seedBuiltinRules(ctx, db)
}

// seedBuiltinRules inserts well-known correlation rules (only if table is empty).
func seedBuiltinRules(ctx context.Context, db *sql.DB) error {
	var count int
	_ = db.QueryRowContext(ctx, `SELECT COUNT(*) FROM kubesense_correlation_rules WHERE auto_generated = FALSE`).Scan(&count)
	if count > 0 {
		return nil // already seeded
	}

	builtins := []struct {
		name, trigger, condType, scope, incType, sev, summary string
		conds                                                  []RuleCondition
	}{
		{
			name: "oom-then-crash", trigger: "health.pod.crashloopbackoff",
			incType: "OOMCrashLoop", sev: "P2",
			summary: "OOM-induced crash loop on {{.Namespace}}/{{.PodName}}",
			conds:   []RuleCondition{{EventType: "health.pod.oomkilled", Scope: "samePod"}},
		},
		{
			name: "node-pressure-eviction", trigger: "health.pod.evicted",
			incType: "NodePressureEviction", sev: "P2",
			summary: "Node pressure evicting pods on node {{.NodeName}}",
			conds:   []RuleCondition{{EventType: "health.node.memory_pressure", Scope: "sameNode"}},
		},
		{
			name: "image-pull-crash", trigger: "health.pod.imagepull_error",
			incType: "DeploymentImageFailure", sev: "P3",
			summary: "Image pull failure causing crash on {{.Namespace}}/{{.PodName}}",
			conds:   []RuleCondition{{EventType: "health.pod.crashloopbackoff", Scope: "samePod"}},
		},
		{
			name: "rollout-degraded", trigger: "change.deployment.rollout",
			incType: "FailedRollout", sev: "P2",
			summary: "Deployment rollout degraded in {{.Namespace}}",
			conds:   []RuleCondition{{EventType: "health.deployment.degraded", Scope: "sameNamespace"}},
		},
		{
			name: "node-notready-eviction", trigger: "health.node.not_ready",
			incType: "NodeFailure", sev: "P1",
			summary: "Node {{.NodeName}} not ready causing pod evictions",
			conds:   []RuleCondition{{EventType: "health.pod.evicted", Scope: "sameNode"}},
		},
		{
			name: "disk-pressure-pvc", trigger: "health.node.disk_pressure",
			incType: "DiskPressure", sev: "P2",
			summary: "Node disk pressure causing PVC issues on {{.NodeName}}",
			conds:   []RuleCondition{{EventType: "storage.pvc.near_full", Scope: "sameNode"}},
		},
		{
			name: "config-change-crash", trigger: "change.configmap.updated",
			incType: "BadConfigRollout", sev: "P3",
			summary: "ConfigMap change correlated with crash loop in {{.Namespace}}",
			conds:   []RuleCondition{{EventType: "health.pod.crashloopbackoff", Scope: "sameNamespace"}},
		},
		{
			name: "secret-rotation-crash", trigger: "change.secret.rotated",
			incType: "SecretRotationFailure", sev: "P3",
			summary: "Secret rotation correlated with crash loop in {{.Namespace}}",
			conds:   []RuleCondition{{EventType: "health.pod.crashloopbackoff", Scope: "sameNamespace"}},
		},
	}

	for _, b := range builtins {
		condJSON, _ := json.Marshal(b.conds)
		_, _ = db.ExecContext(ctx, `
			INSERT INTO kubesense_correlation_rules
			    (name, priority, trigger_event_type, conditions, fires_incident_type,
			     fires_severity, fires_summary, scope, auto_generated)
			VALUES ($1, 100, $2, $3, $4, $5, $6, 'samePod', FALSE)
			ON CONFLICT (name) DO NOTHING
		`, b.name, b.trigger, condJSON, b.incType, b.sev, b.summary)
	}
	return nil
}

// UpsertAutoRule inserts or updates an auto-generated correlation rule.
func UpsertAutoRule(ctx context.Context, db *sql.DB, name, trigger, condType, scope, incType, sev, summary string, dataPoints int, firstSeen, lastSeen time.Time) error {
	conds, _ := json.Marshal([]RuleCondition{{EventType: condType, Scope: scope}})
	expiresAt := lastSeen.Add(1 * time.Hour)
	_, err := db.ExecContext(ctx, `
		INSERT INTO kubesense_correlation_rules
		    (name, priority, trigger_event_type, conditions, fires_incident_type,
		     fires_severity, fires_summary, scope, auto_generated, data_points,
		     first_seen, last_seen, expires_at, updated_at)
		VALUES ($1, 30, $2, $3, $4, $5, $6, $7, TRUE, $8, $9, $10, $11, NOW())
		ON CONFLICT (name) DO UPDATE SET
		    data_points = EXCLUDED.data_points,
		    last_seen   = EXCLUDED.last_seen,
		    expires_at  = EXCLUDED.expires_at,
		    updated_at  = NOW()
	`, name, trigger, conds, incType, sev, summary, scope, dataPoints, firstSeen, lastSeen, expiresAt)
	return err
}

// helper to avoid using strings package import just for one use
func containsStr(s, sub string) bool {
	return strings.Contains(s, sub)
}
