// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/topology_knowledge/topology_knowledge_service.proto

package topology_knowledge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyKnowledgeService_CreateNode_FullMethodName             = "/topology_knowledge.TopologyKnowledgeService/CreateNode"
	TopologyKnowledgeService_GetNode_FullMethodName                = "/topology_knowledge.TopologyKnowledgeService/GetNode"
	TopologyKnowledgeService_UpdateNode_FullMethodName             = "/topology_knowledge.TopologyKnowledgeService/UpdateNode"
	TopologyKnowledgeService_DeleteNode_FullMethodName             = "/topology_knowledge.TopologyKnowledgeService/DeleteNode"
	TopologyKnowledgeService_ListNodes_FullMethodName              = "/topology_knowledge.TopologyKnowledgeService/ListNodes"
	TopologyKnowledgeService_SearchNodes_FullMethodName            = "/topology_knowledge.TopologyKnowledgeService/SearchNodes"
	TopologyKnowledgeService_CreateRelationship_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/CreateRelationship"
	TopologyKnowledgeService_GetRelationship_FullMethodName        = "/topology_knowledge.TopologyKnowledgeService/GetRelationship"
	TopologyKnowledgeService_UpdateRelationship_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/UpdateRelationship"
	TopologyKnowledgeService_DeleteRelationship_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/DeleteRelationship"
	TopologyKnowledgeService_ListRelationships_FullMethodName      = "/topology_knowledge.TopologyKnowledgeService/ListRelationships"
	TopologyKnowledgeService_StartDiscovery_FullMethodName         = "/topology_knowledge.TopologyKnowledgeService/StartDiscovery"
	TopologyKnowledgeService_GetDiscoveryStatus_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/GetDiscoveryStatus"
	TopologyKnowledgeService_ListDiscoveries_FullMethodName        = "/topology_knowledge.TopologyKnowledgeService/ListDiscoveries"
	TopologyKnowledgeService_StopDiscovery_FullMethodName          = "/topology_knowledge.TopologyKnowledgeService/StopDiscovery"
	TopologyKnowledgeService_GetTopology_FullMethodName            = "/topology_knowledge.TopologyKnowledgeService/GetTopology"
	TopologyKnowledgeService_GetSubTopology_FullMethodName         = "/topology_knowledge.TopologyKnowledgeService/GetSubTopology"
	TopologyKnowledgeService_GetNodeNeighbors_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/GetNodeNeighbors"
	TopologyKnowledgeService_GetPath_FullMethodName                = "/topology_knowledge.TopologyKnowledgeService/GetPath"
	TopologyKnowledgeService_FindShortestPath_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/FindShortestPath"
	TopologyKnowledgeService_AnalyzeImpact_FullMethodName          = "/topology_knowledge.TopologyKnowledgeService/AnalyzeImpact"
	TopologyKnowledgeService_GetDependencies_FullMethodName        = "/topology_knowledge.TopologyKnowledgeService/GetDependencies"
	TopologyKnowledgeService_GetDependents_FullMethodName          = "/topology_knowledge.TopologyKnowledgeService/GetDependents"
	TopologyKnowledgeService_CalculateBlastRadius_FullMethodName   = "/topology_knowledge.TopologyKnowledgeService/CalculateBlastRadius"
	TopologyKnowledgeService_GetTopologyChanges_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/GetTopologyChanges"
	TopologyKnowledgeService_GetChangeHistory_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/GetChangeHistory"
	TopologyKnowledgeService_CreateSnapshot_FullMethodName         = "/topology_knowledge.TopologyKnowledgeService/CreateSnapshot"
	TopologyKnowledgeService_RestoreSnapshot_FullMethodName        = "/topology_knowledge.TopologyKnowledgeService/RestoreSnapshot"
	TopologyKnowledgeService_ValidateTopology_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/ValidateTopology"
	TopologyKnowledgeService_DetectAnomalies_FullMethodName        = "/topology_knowledge.TopologyKnowledgeService/DetectAnomalies"
	TopologyKnowledgeService_CheckConsistency_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/CheckConsistency"
	TopologyKnowledgeService_SyncTopology_FullMethodName           = "/topology_knowledge.TopologyKnowledgeService/SyncTopology"
	TopologyKnowledgeService_GetSyncStatus_FullMethodName          = "/topology_knowledge.TopologyKnowledgeService/GetSyncStatus"
	TopologyKnowledgeService_WatchTopologyChanges_FullMethodName   = "/topology_knowledge.TopologyKnowledgeService/WatchTopologyChanges"
	TopologyKnowledgeService_WatchNodeChanges_FullMethodName       = "/topology_knowledge.TopologyKnowledgeService/WatchNodeChanges"
	TopologyKnowledgeService_GetTopologyMetrics_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/GetTopologyMetrics"
	TopologyKnowledgeService_GetNodeMetrics_FullMethodName         = "/topology_knowledge.TopologyKnowledgeService/GetNodeMetrics"
	TopologyKnowledgeService_GetRelationshipMetrics_FullMethodName = "/topology_knowledge.TopologyKnowledgeService/GetRelationshipMetrics"
	TopologyKnowledgeService_UpdateDiscoveryConfig_FullMethodName  = "/topology_knowledge.TopologyKnowledgeService/UpdateDiscoveryConfig"
	TopologyKnowledgeService_GetDiscoveryConfig_FullMethodName     = "/topology_knowledge.TopologyKnowledgeService/GetDiscoveryConfig"
)

// TopologyKnowledgeServiceClient is the client API for TopologyKnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Topology Knowledge Service Definition
type TopologyKnowledgeServiceClient interface {
	// Node management
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error)
	// Relationship management
	CreateRelationship(ctx context.Context, in *CreateRelationshipRequest, opts ...grpc.CallOption) (*CreateRelationshipResponse, error)
	GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error)
	UpdateRelationship(ctx context.Context, in *UpdateRelationshipRequest, opts ...grpc.CallOption) (*UpdateRelationshipResponse, error)
	DeleteRelationship(ctx context.Context, in *DeleteRelationshipRequest, opts ...grpc.CallOption) (*DeleteRelationshipResponse, error)
	ListRelationships(ctx context.Context, in *ListRelationshipsRequest, opts ...grpc.CallOption) (*ListRelationshipsResponse, error)
	// Topology discovery
	StartDiscovery(ctx context.Context, in *StartDiscoveryRequest, opts ...grpc.CallOption) (*StartDiscoveryResponse, error)
	GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*GetDiscoveryStatusResponse, error)
	ListDiscoveries(ctx context.Context, in *ListDiscoveriesRequest, opts ...grpc.CallOption) (*ListDiscoveriesResponse, error)
	StopDiscovery(ctx context.Context, in *StopDiscoveryRequest, opts ...grpc.CallOption) (*StopDiscoveryResponse, error)
	// Topology queries
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	GetSubTopology(ctx context.Context, in *GetSubTopologyRequest, opts ...grpc.CallOption) (*GetSubTopologyResponse, error)
	GetNodeNeighbors(ctx context.Context, in *GetNodeNeighborsRequest, opts ...grpc.CallOption) (*GetNodeNeighborsResponse, error)
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error)
	FindShortestPath(ctx context.Context, in *FindShortestPathRequest, opts ...grpc.CallOption) (*FindShortestPathResponse, error)
	// Impact analysis
	AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error)
	GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error)
	GetDependents(ctx context.Context, in *GetDependentsRequest, opts ...grpc.CallOption) (*GetDependentsResponse, error)
	CalculateBlastRadius(ctx context.Context, in *CalculateBlastRadiusRequest, opts ...grpc.CallOption) (*CalculateBlastRadiusResponse, error)
	// Change tracking
	GetTopologyChanges(ctx context.Context, in *GetTopologyChangesRequest, opts ...grpc.CallOption) (*GetTopologyChangesResponse, error)
	GetChangeHistory(ctx context.Context, in *GetChangeHistoryRequest, opts ...grpc.CallOption) (*GetChangeHistoryResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error)
	// Topology validation
	ValidateTopology(ctx context.Context, in *ValidateTopologyRequest, opts ...grpc.CallOption) (*ValidateTopologyResponse, error)
	DetectAnomalies(ctx context.Context, in *DetectAnomaliesRequest, opts ...grpc.CallOption) (*DetectAnomaliesResponse, error)
	CheckConsistency(ctx context.Context, in *CheckConsistencyRequest, opts ...grpc.CallOption) (*CheckConsistencyResponse, error)
	// Topology synchronization
	SyncTopology(ctx context.Context, in *SyncTopologyRequest, opts ...grpc.CallOption) (*SyncTopologyResponse, error)
	GetSyncStatus(ctx context.Context, in *GetSyncStatusRequest, opts ...grpc.CallOption) (*GetSyncStatusResponse, error)
	// Topology watching
	WatchTopologyChanges(ctx context.Context, in *WatchTopologyChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyChangeEvent], error)
	WatchNodeChanges(ctx context.Context, in *WatchNodeChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeChangeEvent], error)
	// Metrics and analytics
	GetTopologyMetrics(ctx context.Context, in *GetTopologyMetricsRequest, opts ...grpc.CallOption) (*GetTopologyMetricsResponse, error)
	GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error)
	GetRelationshipMetrics(ctx context.Context, in *GetRelationshipMetricsRequest, opts ...grpc.CallOption) (*GetRelationshipMetricsResponse, error)
	// Configuration management
	UpdateDiscoveryConfig(ctx context.Context, in *UpdateDiscoveryConfigRequest, opts ...grpc.CallOption) (*UpdateDiscoveryConfigResponse, error)
	GetDiscoveryConfig(ctx context.Context, in *GetDiscoveryConfigRequest, opts ...grpc.CallOption) (*GetDiscoveryConfigResponse, error)
}

type topologyKnowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyKnowledgeServiceClient(cc grpc.ClientConnInterface) TopologyKnowledgeServiceClient {
	return &topologyKnowledgeServiceClient{cc}
}

func (c *topologyKnowledgeServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchNodesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_SearchNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) CreateRelationship(ctx context.Context, in *CreateRelationshipRequest, opts ...grpc.CallOption) (*CreateRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRelationshipResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_CreateRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationshipResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) UpdateRelationship(ctx context.Context, in *UpdateRelationshipRequest, opts ...grpc.CallOption) (*UpdateRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRelationshipResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_UpdateRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) DeleteRelationship(ctx context.Context, in *DeleteRelationshipRequest, opts ...grpc.CallOption) (*DeleteRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRelationshipResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_DeleteRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) ListRelationships(ctx context.Context, in *ListRelationshipsRequest, opts ...grpc.CallOption) (*ListRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRelationshipsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_ListRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) StartDiscovery(ctx context.Context, in *StartDiscoveryRequest, opts ...grpc.CallOption) (*StartDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDiscoveryResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_StartDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetDiscoveryStatus(ctx context.Context, in *GetDiscoveryStatusRequest, opts ...grpc.CallOption) (*GetDiscoveryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscoveryStatusResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetDiscoveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) ListDiscoveries(ctx context.Context, in *ListDiscoveriesRequest, opts ...grpc.CallOption) (*ListDiscoveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiscoveriesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_ListDiscoveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) StopDiscovery(ctx context.Context, in *StopDiscoveryRequest, opts ...grpc.CallOption) (*StopDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDiscoveryResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_StopDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetSubTopology(ctx context.Context, in *GetSubTopologyRequest, opts ...grpc.CallOption) (*GetSubTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetSubTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetNodeNeighbors(ctx context.Context, in *GetNodeNeighborsRequest, opts ...grpc.CallOption) (*GetNodeNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeNeighborsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetNodeNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPathResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) FindShortestPath(ctx context.Context, in *FindShortestPathRequest, opts ...grpc.CallOption) (*FindShortestPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindShortestPathResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_FindShortestPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) AnalyzeImpact(ctx context.Context, in *AnalyzeImpactRequest, opts ...grpc.CallOption) (*AnalyzeImpactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeImpactResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_AnalyzeImpact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDependenciesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetDependents(ctx context.Context, in *GetDependentsRequest, opts ...grpc.CallOption) (*GetDependentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDependentsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetDependents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) CalculateBlastRadius(ctx context.Context, in *CalculateBlastRadiusRequest, opts ...grpc.CallOption) (*CalculateBlastRadiusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateBlastRadiusResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_CalculateBlastRadius_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetTopologyChanges(ctx context.Context, in *GetTopologyChangesRequest, opts ...grpc.CallOption) (*GetTopologyChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyChangesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetTopologyChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetChangeHistory(ctx context.Context, in *GetChangeHistoryRequest, opts ...grpc.CallOption) (*GetChangeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChangeHistoryResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetChangeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*RestoreSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreSnapshotResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) ValidateTopology(ctx context.Context, in *ValidateTopologyRequest, opts ...grpc.CallOption) (*ValidateTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_ValidateTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) DetectAnomalies(ctx context.Context, in *DetectAnomaliesRequest, opts ...grpc.CallOption) (*DetectAnomaliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectAnomaliesResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_DetectAnomalies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) CheckConsistency(ctx context.Context, in *CheckConsistencyRequest, opts ...grpc.CallOption) (*CheckConsistencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConsistencyResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_CheckConsistency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) SyncTopology(ctx context.Context, in *SyncTopologyRequest, opts ...grpc.CallOption) (*SyncTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncTopologyResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_SyncTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetSyncStatus(ctx context.Context, in *GetSyncStatusRequest, opts ...grpc.CallOption) (*GetSyncStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncStatusResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) WatchTopologyChanges(ctx context.Context, in *WatchTopologyChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyKnowledgeService_ServiceDesc.Streams[0], TopologyKnowledgeService_WatchTopologyChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTopologyChangesRequest, TopologyChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyKnowledgeService_WatchTopologyChangesClient = grpc.ServerStreamingClient[TopologyChangeEvent]

func (c *topologyKnowledgeServiceClient) WatchNodeChanges(ctx context.Context, in *WatchNodeChangesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyKnowledgeService_ServiceDesc.Streams[1], TopologyKnowledgeService_WatchNodeChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchNodeChangesRequest, NodeChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyKnowledgeService_WatchNodeChangesClient = grpc.ServerStreamingClient[NodeChangeEvent]

func (c *topologyKnowledgeServiceClient) GetTopologyMetrics(ctx context.Context, in *GetTopologyMetricsRequest, opts ...grpc.CallOption) (*GetTopologyMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyMetricsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetTopologyMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetNodeMetrics(ctx context.Context, in *GetNodeMetricsRequest, opts ...grpc.CallOption) (*GetNodeMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeMetricsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetNodeMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetRelationshipMetrics(ctx context.Context, in *GetRelationshipMetricsRequest, opts ...grpc.CallOption) (*GetRelationshipMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationshipMetricsResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetRelationshipMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) UpdateDiscoveryConfig(ctx context.Context, in *UpdateDiscoveryConfigRequest, opts ...grpc.CallOption) (*UpdateDiscoveryConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDiscoveryConfigResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_UpdateDiscoveryConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *topologyKnowledgeServiceClient) GetDiscoveryConfig(ctx context.Context, in *GetDiscoveryConfigRequest, opts ...grpc.CallOption) (*GetDiscoveryConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscoveryConfigResponse)
	err := c.cc.Invoke(ctx, TopologyKnowledgeService_GetDiscoveryConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopologyKnowledgeServiceServer is the server API for TopologyKnowledgeService service.
// All implementations must embed UnimplementedTopologyKnowledgeServiceServer
// for forward compatibility.
//
// Topology Knowledge Service Definition
type TopologyKnowledgeServiceServer interface {
	// Node management
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error)
	// Relationship management
	CreateRelationship(context.Context, *CreateRelationshipRequest) (*CreateRelationshipResponse, error)
	GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error)
	UpdateRelationship(context.Context, *UpdateRelationshipRequest) (*UpdateRelationshipResponse, error)
	DeleteRelationship(context.Context, *DeleteRelationshipRequest) (*DeleteRelationshipResponse, error)
	ListRelationships(context.Context, *ListRelationshipsRequest) (*ListRelationshipsResponse, error)
	// Topology discovery
	StartDiscovery(context.Context, *StartDiscoveryRequest) (*StartDiscoveryResponse, error)
	GetDiscoveryStatus(context.Context, *GetDiscoveryStatusRequest) (*GetDiscoveryStatusResponse, error)
	ListDiscoveries(context.Context, *ListDiscoveriesRequest) (*ListDiscoveriesResponse, error)
	StopDiscovery(context.Context, *StopDiscoveryRequest) (*StopDiscoveryResponse, error)
	// Topology queries
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	GetSubTopology(context.Context, *GetSubTopologyRequest) (*GetSubTopologyResponse, error)
	GetNodeNeighbors(context.Context, *GetNodeNeighborsRequest) (*GetNodeNeighborsResponse, error)
	GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error)
	FindShortestPath(context.Context, *FindShortestPathRequest) (*FindShortestPathResponse, error)
	// Impact analysis
	AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error)
	GetDependencies(context.Context, *GetDependenciesRequest) (*GetDependenciesResponse, error)
	GetDependents(context.Context, *GetDependentsRequest) (*GetDependentsResponse, error)
	CalculateBlastRadius(context.Context, *CalculateBlastRadiusRequest) (*CalculateBlastRadiusResponse, error)
	// Change tracking
	GetTopologyChanges(context.Context, *GetTopologyChangesRequest) (*GetTopologyChangesResponse, error)
	GetChangeHistory(context.Context, *GetChangeHistoryRequest) (*GetChangeHistoryResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error)
	// Topology validation
	ValidateTopology(context.Context, *ValidateTopologyRequest) (*ValidateTopologyResponse, error)
	DetectAnomalies(context.Context, *DetectAnomaliesRequest) (*DetectAnomaliesResponse, error)
	CheckConsistency(context.Context, *CheckConsistencyRequest) (*CheckConsistencyResponse, error)
	// Topology synchronization
	SyncTopology(context.Context, *SyncTopologyRequest) (*SyncTopologyResponse, error)
	GetSyncStatus(context.Context, *GetSyncStatusRequest) (*GetSyncStatusResponse, error)
	// Topology watching
	WatchTopologyChanges(*WatchTopologyChangesRequest, grpc.ServerStreamingServer[TopologyChangeEvent]) error
	WatchNodeChanges(*WatchNodeChangesRequest, grpc.ServerStreamingServer[NodeChangeEvent]) error
	// Metrics and analytics
	GetTopologyMetrics(context.Context, *GetTopologyMetricsRequest) (*GetTopologyMetricsResponse, error)
	GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error)
	GetRelationshipMetrics(context.Context, *GetRelationshipMetricsRequest) (*GetRelationshipMetricsResponse, error)
	// Configuration management
	UpdateDiscoveryConfig(context.Context, *UpdateDiscoveryConfigRequest) (*UpdateDiscoveryConfigResponse, error)
	GetDiscoveryConfig(context.Context, *GetDiscoveryConfigRequest) (*GetDiscoveryConfigResponse, error)
	mustEmbedUnimplementedTopologyKnowledgeServiceServer()
}

// UnimplementedTopologyKnowledgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyKnowledgeServiceServer struct{}

func (UnimplementedTopologyKnowledgeServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchNodes not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) CreateRelationship(context.Context, *CreateRelationshipRequest) (*CreateRelationshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRelationship not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelationship not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) UpdateRelationship(context.Context, *UpdateRelationshipRequest) (*UpdateRelationshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRelationship not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) DeleteRelationship(context.Context, *DeleteRelationshipRequest) (*DeleteRelationshipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRelationship not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) ListRelationships(context.Context, *ListRelationshipsRequest) (*ListRelationshipsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelationships not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) StartDiscovery(context.Context, *StartDiscoveryRequest) (*StartDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDiscovery not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetDiscoveryStatus(context.Context, *GetDiscoveryStatusRequest) (*GetDiscoveryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscoveryStatus not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) ListDiscoveries(context.Context, *ListDiscoveriesRequest) (*ListDiscoveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDiscoveries not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) StopDiscovery(context.Context, *StopDiscoveryRequest) (*StopDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDiscovery not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetSubTopology(context.Context, *GetSubTopologyRequest) (*GetSubTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubTopology not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetNodeNeighbors(context.Context, *GetNodeNeighborsRequest) (*GetNodeNeighborsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeNeighbors not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) FindShortestPath(context.Context, *FindShortestPathRequest) (*FindShortestPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindShortestPath not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) AnalyzeImpact(context.Context, *AnalyzeImpactRequest) (*AnalyzeImpactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeImpact not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetDependencies(context.Context, *GetDependenciesRequest) (*GetDependenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetDependents(context.Context, *GetDependentsRequest) (*GetDependentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDependents not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) CalculateBlastRadius(context.Context, *CalculateBlastRadiusRequest) (*CalculateBlastRadiusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBlastRadius not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetTopologyChanges(context.Context, *GetTopologyChangesRequest) (*GetTopologyChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopologyChanges not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetChangeHistory(context.Context, *GetChangeHistoryRequest) (*GetChangeHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChangeHistory not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*RestoreSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) ValidateTopology(context.Context, *ValidateTopologyRequest) (*ValidateTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateTopology not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) DetectAnomalies(context.Context, *DetectAnomaliesRequest) (*DetectAnomaliesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectAnomalies not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) CheckConsistency(context.Context, *CheckConsistencyRequest) (*CheckConsistencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConsistency not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) SyncTopology(context.Context, *SyncTopologyRequest) (*SyncTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncTopology not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetSyncStatus(context.Context, *GetSyncStatusRequest) (*GetSyncStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) WatchTopologyChanges(*WatchTopologyChangesRequest, grpc.ServerStreamingServer[TopologyChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTopologyChanges not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) WatchNodeChanges(*WatchNodeChangesRequest, grpc.ServerStreamingServer[NodeChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchNodeChanges not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetTopologyMetrics(context.Context, *GetTopologyMetricsRequest) (*GetTopologyMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopologyMetrics not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetNodeMetrics(context.Context, *GetNodeMetricsRequest) (*GetNodeMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeMetrics not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetRelationshipMetrics(context.Context, *GetRelationshipMetricsRequest) (*GetRelationshipMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelationshipMetrics not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) UpdateDiscoveryConfig(context.Context, *UpdateDiscoveryConfigRequest) (*UpdateDiscoveryConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDiscoveryConfig not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) GetDiscoveryConfig(context.Context, *GetDiscoveryConfigRequest) (*GetDiscoveryConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiscoveryConfig not implemented")
}
func (UnimplementedTopologyKnowledgeServiceServer) mustEmbedUnimplementedTopologyKnowledgeServiceServer() {
}
func (UnimplementedTopologyKnowledgeServiceServer) testEmbeddedByValue() {}

// UnsafeTopologyKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyKnowledgeServiceServer will
// result in compilation errors.
type UnsafeTopologyKnowledgeServiceServer interface {
	mustEmbedUnimplementedTopologyKnowledgeServiceServer()
}

func RegisterTopologyKnowledgeServiceServer(s grpc.ServiceRegistrar, srv TopologyKnowledgeServiceServer) {
	// If the following call panics, it indicates UnimplementedTopologyKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyKnowledgeService_ServiceDesc, srv)
}

func _TopologyKnowledgeService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).SearchNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_SearchNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).SearchNodes(ctx, req.(*SearchNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_CreateRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).CreateRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_CreateRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).CreateRelationship(ctx, req.(*CreateRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetRelationship(ctx, req.(*GetRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_UpdateRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).UpdateRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_UpdateRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).UpdateRelationship(ctx, req.(*UpdateRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_DeleteRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).DeleteRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_DeleteRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).DeleteRelationship(ctx, req.(*DeleteRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_ListRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).ListRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_ListRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).ListRelationships(ctx, req.(*ListRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_StartDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).StartDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_StartDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).StartDiscovery(ctx, req.(*StartDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetDiscoveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscoveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetDiscoveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetDiscoveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetDiscoveryStatus(ctx, req.(*GetDiscoveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_ListDiscoveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiscoveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).ListDiscoveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_ListDiscoveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).ListDiscoveries(ctx, req.(*ListDiscoveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_StopDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).StopDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_StopDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).StopDiscovery(ctx, req.(*StopDiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetSubTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetSubTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetSubTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetSubTopology(ctx, req.(*GetSubTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetNodeNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetNodeNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetNodeNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetNodeNeighbors(ctx, req.(*GetNodeNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_FindShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).FindShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_FindShortestPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).FindShortestPath(ctx, req.(*FindShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_AnalyzeImpact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeImpactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).AnalyzeImpact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_AnalyzeImpact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).AnalyzeImpact(ctx, req.(*AnalyzeImpactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetDependencies(ctx, req.(*GetDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetDependents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetDependents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetDependents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetDependents(ctx, req.(*GetDependentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_CalculateBlastRadius_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateBlastRadiusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).CalculateBlastRadius(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_CalculateBlastRadius_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).CalculateBlastRadius(ctx, req.(*CalculateBlastRadiusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetTopologyChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetTopologyChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetTopologyChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetTopologyChanges(ctx, req.(*GetTopologyChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetChangeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangeHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetChangeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetChangeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetChangeHistory(ctx, req.(*GetChangeHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_ValidateTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).ValidateTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_ValidateTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).ValidateTopology(ctx, req.(*ValidateTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_DetectAnomalies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectAnomaliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).DetectAnomalies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_DetectAnomalies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).DetectAnomalies(ctx, req.(*DetectAnomaliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_CheckConsistency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConsistencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).CheckConsistency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_CheckConsistency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).CheckConsistency(ctx, req.(*CheckConsistencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_SyncTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).SyncTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_SyncTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).SyncTopology(ctx, req.(*SyncTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetSyncStatus(ctx, req.(*GetSyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_WatchTopologyChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTopologyChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyKnowledgeServiceServer).WatchTopologyChanges(m, &grpc.GenericServerStream[WatchTopologyChangesRequest, TopologyChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyKnowledgeService_WatchTopologyChangesServer = grpc.ServerStreamingServer[TopologyChangeEvent]

func _TopologyKnowledgeService_WatchNodeChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchNodeChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyKnowledgeServiceServer).WatchNodeChanges(m, &grpc.GenericServerStream[WatchNodeChangesRequest, NodeChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyKnowledgeService_WatchNodeChangesServer = grpc.ServerStreamingServer[NodeChangeEvent]

func _TopologyKnowledgeService_GetTopologyMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetTopologyMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetTopologyMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetTopologyMetrics(ctx, req.(*GetTopologyMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetNodeMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetNodeMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetNodeMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetNodeMetrics(ctx, req.(*GetNodeMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetRelationshipMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationshipMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetRelationshipMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetRelationshipMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetRelationshipMetrics(ctx, req.(*GetRelationshipMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_UpdateDiscoveryConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiscoveryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).UpdateDiscoveryConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_UpdateDiscoveryConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).UpdateDiscoveryConfig(ctx, req.(*UpdateDiscoveryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TopologyKnowledgeService_GetDiscoveryConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscoveryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyKnowledgeServiceServer).GetDiscoveryConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyKnowledgeService_GetDiscoveryConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyKnowledgeServiceServer).GetDiscoveryConfig(ctx, req.(*GetDiscoveryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopologyKnowledgeService_ServiceDesc is the grpc.ServiceDesc for TopologyKnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyKnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "topology_knowledge.TopologyKnowledgeService",
	HandlerType: (*TopologyKnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNode",
			Handler:    _TopologyKnowledgeService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _TopologyKnowledgeService_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _TopologyKnowledgeService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _TopologyKnowledgeService_DeleteNode_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _TopologyKnowledgeService_ListNodes_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _TopologyKnowledgeService_SearchNodes_Handler,
		},
		{
			MethodName: "CreateRelationship",
			Handler:    _TopologyKnowledgeService_CreateRelationship_Handler,
		},
		{
			MethodName: "GetRelationship",
			Handler:    _TopologyKnowledgeService_GetRelationship_Handler,
		},
		{
			MethodName: "UpdateRelationship",
			Handler:    _TopologyKnowledgeService_UpdateRelationship_Handler,
		},
		{
			MethodName: "DeleteRelationship",
			Handler:    _TopologyKnowledgeService_DeleteRelationship_Handler,
		},
		{
			MethodName: "ListRelationships",
			Handler:    _TopologyKnowledgeService_ListRelationships_Handler,
		},
		{
			MethodName: "StartDiscovery",
			Handler:    _TopologyKnowledgeService_StartDiscovery_Handler,
		},
		{
			MethodName: "GetDiscoveryStatus",
			Handler:    _TopologyKnowledgeService_GetDiscoveryStatus_Handler,
		},
		{
			MethodName: "ListDiscoveries",
			Handler:    _TopologyKnowledgeService_ListDiscoveries_Handler,
		},
		{
			MethodName: "StopDiscovery",
			Handler:    _TopologyKnowledgeService_StopDiscovery_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _TopologyKnowledgeService_GetTopology_Handler,
		},
		{
			MethodName: "GetSubTopology",
			Handler:    _TopologyKnowledgeService_GetSubTopology_Handler,
		},
		{
			MethodName: "GetNodeNeighbors",
			Handler:    _TopologyKnowledgeService_GetNodeNeighbors_Handler,
		},
		{
			MethodName: "GetPath",
			Handler:    _TopologyKnowledgeService_GetPath_Handler,
		},
		{
			MethodName: "FindShortestPath",
			Handler:    _TopologyKnowledgeService_FindShortestPath_Handler,
		},
		{
			MethodName: "AnalyzeImpact",
			Handler:    _TopologyKnowledgeService_AnalyzeImpact_Handler,
		},
		{
			MethodName: "GetDependencies",
			Handler:    _TopologyKnowledgeService_GetDependencies_Handler,
		},
		{
			MethodName: "GetDependents",
			Handler:    _TopologyKnowledgeService_GetDependents_Handler,
		},
		{
			MethodName: "CalculateBlastRadius",
			Handler:    _TopologyKnowledgeService_CalculateBlastRadius_Handler,
		},
		{
			MethodName: "GetTopologyChanges",
			Handler:    _TopologyKnowledgeService_GetTopologyChanges_Handler,
		},
		{
			MethodName: "GetChangeHistory",
			Handler:    _TopologyKnowledgeService_GetChangeHistory_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _TopologyKnowledgeService_CreateSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _TopologyKnowledgeService_RestoreSnapshot_Handler,
		},
		{
			MethodName: "ValidateTopology",
			Handler:    _TopologyKnowledgeService_ValidateTopology_Handler,
		},
		{
			MethodName: "DetectAnomalies",
			Handler:    _TopologyKnowledgeService_DetectAnomalies_Handler,
		},
		{
			MethodName: "CheckConsistency",
			Handler:    _TopologyKnowledgeService_CheckConsistency_Handler,
		},
		{
			MethodName: "SyncTopology",
			Handler:    _TopologyKnowledgeService_SyncTopology_Handler,
		},
		{
			MethodName: "GetSyncStatus",
			Handler:    _TopologyKnowledgeService_GetSyncStatus_Handler,
		},
		{
			MethodName: "GetTopologyMetrics",
			Handler:    _TopologyKnowledgeService_GetTopologyMetrics_Handler,
		},
		{
			MethodName: "GetNodeMetrics",
			Handler:    _TopologyKnowledgeService_GetNodeMetrics_Handler,
		},
		{
			MethodName: "GetRelationshipMetrics",
			Handler:    _TopologyKnowledgeService_GetRelationshipMetrics_Handler,
		},
		{
			MethodName: "UpdateDiscoveryConfig",
			Handler:    _TopologyKnowledgeService_UpdateDiscoveryConfig_Handler,
		},
		{
			MethodName: "GetDiscoveryConfig",
			Handler:    _TopologyKnowledgeService_GetDiscoveryConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTopologyChanges",
			Handler:       _TopologyKnowledgeService_WatchTopologyChanges_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchNodeChanges",
			Handler:       _TopologyKnowledgeService_WatchNodeChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/topology_knowledge/topology_knowledge_service.proto",
}
