# ============================================================
# alerthub-oie — mps-tooling-mdn overrides (DR / Warm Standby)
# ============================================================

global:
  storageClass: tooling-mdn-netapp-default
  namespace: alert-engine

build:
  enabled: false

whisper:
  enabled: true

oie:
  replicas: 1
