apiVersion: v1
kind: Service
metadata:
  name: rca-orchestrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alerthub.labels" . | nindent 4 }}
    app.kubernetes.io/component: rca-orchestrator
    app: rca-orchestrator
spec:
  type: ClusterIP
  selector:
    app: rca-orchestrator
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP
