// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/alert_management/alert_management_service.proto

package alert_management

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertManagementService_CreateAlert_FullMethodName         = "/alert_management.AlertManagementService/CreateAlert"
	AlertManagementService_GetAlert_FullMethodName            = "/alert_management.AlertManagementService/GetAlert"
	AlertManagementService_UpdateAlert_FullMethodName         = "/alert_management.AlertManagementService/UpdateAlert"
	AlertManagementService_DeleteAlert_FullMethodName         = "/alert_management.AlertManagementService/DeleteAlert"
	AlertManagementService_ListAlerts_FullMethodName          = "/alert_management.AlertManagementService/ListAlerts"
	AlertManagementService_SearchAlerts_FullMethodName        = "/alert_management.AlertManagementService/SearchAlerts"
	AlertManagementService_CorrelateAlert_FullMethodName      = "/alert_management.AlertManagementService/CorrelateAlert"
	AlertManagementService_GetCorrelatedAlerts_FullMethodName = "/alert_management.AlertManagementService/GetCorrelatedAlerts"
	AlertManagementService_EnrichAlert_FullMethodName         = "/alert_management.AlertManagementService/EnrichAlert"
	AlertManagementService_GetAlertContext_FullMethodName     = "/alert_management.AlertManagementService/GetAlertContext"
	AlertManagementService_DetectBurst_FullMethodName         = "/alert_management.AlertManagementService/DetectBurst"
	AlertManagementService_GetBurstMetrics_FullMethodName     = "/alert_management.AlertManagementService/GetBurstMetrics"
	AlertManagementService_AcknowledgeAlert_FullMethodName    = "/alert_management.AlertManagementService/AcknowledgeAlert"
	AlertManagementService_ResolveAlert_FullMethodName        = "/alert_management.AlertManagementService/ResolveAlert"
	AlertManagementService_EscalateAlert_FullMethodName       = "/alert_management.AlertManagementService/EscalateAlert"
	AlertManagementService_ApplyFloodgate_FullMethodName      = "/alert_management.AlertManagementService/ApplyFloodgate"
	AlertManagementService_GetSuppressionRules_FullMethodName = "/alert_management.AlertManagementService/GetSuppressionRules"
	AlertManagementService_GetAlertMetrics_FullMethodName     = "/alert_management.AlertManagementService/GetAlertMetrics"
	AlertManagementService_GetAlertTrends_FullMethodName      = "/alert_management.AlertManagementService/GetAlertTrends"
)

// AlertManagementServiceClient is the client API for AlertManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Alert Management Service Definition
type AlertManagementServiceClient interface {
	// Alert operations
	CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error)
	GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error)
	UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*UpdateAlertResponse, error)
	DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error)
	ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error)
	SearchAlerts(ctx context.Context, in *SearchAlertsRequest, opts ...grpc.CallOption) (*SearchAlertsResponse, error)
	// Alert correlation
	CorrelateAlert(ctx context.Context, in *CorrelateAlertRequest, opts ...grpc.CallOption) (*CorrelateAlertResponse, error)
	GetCorrelatedAlerts(ctx context.Context, in *GetCorrelatedAlertsRequest, opts ...grpc.CallOption) (*GetCorrelatedAlertsResponse, error)
	// Alert enrichment
	EnrichAlert(ctx context.Context, in *EnrichAlertRequest, opts ...grpc.CallOption) (*EnrichAlertResponse, error)
	GetAlertContext(ctx context.Context, in *GetAlertContextRequest, opts ...grpc.CallOption) (*GetAlertContextResponse, error)
	// Burst detection
	DetectBurst(ctx context.Context, in *DetectBurstRequest, opts ...grpc.CallOption) (*DetectBurstResponse, error)
	GetBurstMetrics(ctx context.Context, in *GetBurstMetricsRequest, opts ...grpc.CallOption) (*GetBurstMetricsResponse, error)
	// Alert lifecycle management
	AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error)
	ResolveAlert(ctx context.Context, in *ResolveAlertRequest, opts ...grpc.CallOption) (*ResolveAlertResponse, error)
	EscalateAlert(ctx context.Context, in *EscalateAlertRequest, opts ...grpc.CallOption) (*EscalateAlertResponse, error)
	// Floodgate and suppression
	ApplyFloodgate(ctx context.Context, in *ApplyFloodgateRequest, opts ...grpc.CallOption) (*ApplyFloodgateResponse, error)
	GetSuppressionRules(ctx context.Context, in *GetSuppressionRulesRequest, opts ...grpc.CallOption) (*GetSuppressionRulesResponse, error)
	// Metrics and analytics
	GetAlertMetrics(ctx context.Context, in *GetAlertMetricsRequest, opts ...grpc.CallOption) (*GetAlertMetricsResponse, error)
	GetAlertTrends(ctx context.Context, in *GetAlertTrendsRequest, opts ...grpc.CallOption) (*GetAlertTrendsResponse, error)
}

type alertManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertManagementServiceClient(cc grpc.ClientConnInterface) AlertManagementServiceClient {
	return &alertManagementServiceClient{cc}
}

func (c *alertManagementServiceClient) CreateAlert(ctx context.Context, in *CreateAlertRequest, opts ...grpc.CallOption) (*CreateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_CreateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetAlert(ctx context.Context, in *GetAlertRequest, opts ...grpc.CallOption) (*GetAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) UpdateAlert(ctx context.Context, in *UpdateAlertRequest, opts ...grpc.CallOption) (*UpdateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_UpdateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) DeleteAlert(ctx context.Context, in *DeleteAlertRequest, opts ...grpc.CallOption) (*DeleteAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_DeleteAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) ListAlerts(ctx context.Context, in *ListAlertsRequest, opts ...grpc.CallOption) (*ListAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlertsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_ListAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) SearchAlerts(ctx context.Context, in *SearchAlertsRequest, opts ...grpc.CallOption) (*SearchAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAlertsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_SearchAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) CorrelateAlert(ctx context.Context, in *CorrelateAlertRequest, opts ...grpc.CallOption) (*CorrelateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CorrelateAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_CorrelateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetCorrelatedAlerts(ctx context.Context, in *GetCorrelatedAlertsRequest, opts ...grpc.CallOption) (*GetCorrelatedAlertsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCorrelatedAlertsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetCorrelatedAlerts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) EnrichAlert(ctx context.Context, in *EnrichAlertRequest, opts ...grpc.CallOption) (*EnrichAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_EnrichAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetAlertContext(ctx context.Context, in *GetAlertContextRequest, opts ...grpc.CallOption) (*GetAlertContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertContextResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetAlertContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) DetectBurst(ctx context.Context, in *DetectBurstRequest, opts ...grpc.CallOption) (*DetectBurstResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectBurstResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_DetectBurst_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetBurstMetrics(ctx context.Context, in *GetBurstMetricsRequest, opts ...grpc.CallOption) (*GetBurstMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBurstMetricsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetBurstMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) AcknowledgeAlert(ctx context.Context, in *AcknowledgeAlertRequest, opts ...grpc.CallOption) (*AcknowledgeAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_AcknowledgeAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) ResolveAlert(ctx context.Context, in *ResolveAlertRequest, opts ...grpc.CallOption) (*ResolveAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_ResolveAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) EscalateAlert(ctx context.Context, in *EscalateAlertRequest, opts ...grpc.CallOption) (*EscalateAlertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EscalateAlertResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_EscalateAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) ApplyFloodgate(ctx context.Context, in *ApplyFloodgateRequest, opts ...grpc.CallOption) (*ApplyFloodgateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyFloodgateResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_ApplyFloodgate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetSuppressionRules(ctx context.Context, in *GetSuppressionRulesRequest, opts ...grpc.CallOption) (*GetSuppressionRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSuppressionRulesResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetSuppressionRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetAlertMetrics(ctx context.Context, in *GetAlertMetricsRequest, opts ...grpc.CallOption) (*GetAlertMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertMetricsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetAlertMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alertManagementServiceClient) GetAlertTrends(ctx context.Context, in *GetAlertTrendsRequest, opts ...grpc.CallOption) (*GetAlertTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertTrendsResponse)
	err := c.cc.Invoke(ctx, AlertManagementService_GetAlertTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertManagementServiceServer is the server API for AlertManagementService service.
// All implementations must embed UnimplementedAlertManagementServiceServer
// for forward compatibility.
//
// Alert Management Service Definition
type AlertManagementServiceServer interface {
	// Alert operations
	CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error)
	GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error)
	UpdateAlert(context.Context, *UpdateAlertRequest) (*UpdateAlertResponse, error)
	DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error)
	ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error)
	SearchAlerts(context.Context, *SearchAlertsRequest) (*SearchAlertsResponse, error)
	// Alert correlation
	CorrelateAlert(context.Context, *CorrelateAlertRequest) (*CorrelateAlertResponse, error)
	GetCorrelatedAlerts(context.Context, *GetCorrelatedAlertsRequest) (*GetCorrelatedAlertsResponse, error)
	// Alert enrichment
	EnrichAlert(context.Context, *EnrichAlertRequest) (*EnrichAlertResponse, error)
	GetAlertContext(context.Context, *GetAlertContextRequest) (*GetAlertContextResponse, error)
	// Burst detection
	DetectBurst(context.Context, *DetectBurstRequest) (*DetectBurstResponse, error)
	GetBurstMetrics(context.Context, *GetBurstMetricsRequest) (*GetBurstMetricsResponse, error)
	// Alert lifecycle management
	AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error)
	ResolveAlert(context.Context, *ResolveAlertRequest) (*ResolveAlertResponse, error)
	EscalateAlert(context.Context, *EscalateAlertRequest) (*EscalateAlertResponse, error)
	// Floodgate and suppression
	ApplyFloodgate(context.Context, *ApplyFloodgateRequest) (*ApplyFloodgateResponse, error)
	GetSuppressionRules(context.Context, *GetSuppressionRulesRequest) (*GetSuppressionRulesResponse, error)
	// Metrics and analytics
	GetAlertMetrics(context.Context, *GetAlertMetricsRequest) (*GetAlertMetricsResponse, error)
	GetAlertTrends(context.Context, *GetAlertTrendsRequest) (*GetAlertTrendsResponse, error)
	mustEmbedUnimplementedAlertManagementServiceServer()
}

// UnimplementedAlertManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertManagementServiceServer struct{}

func (UnimplementedAlertManagementServiceServer) CreateAlert(context.Context, *CreateAlertRequest) (*CreateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetAlert(context.Context, *GetAlertRequest) (*GetAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) UpdateAlert(context.Context, *UpdateAlertRequest) (*UpdateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) DeleteAlert(context.Context, *DeleteAlertRequest) (*DeleteAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) ListAlerts(context.Context, *ListAlertsRequest) (*ListAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlerts not implemented")
}
func (UnimplementedAlertManagementServiceServer) SearchAlerts(context.Context, *SearchAlertsRequest) (*SearchAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAlerts not implemented")
}
func (UnimplementedAlertManagementServiceServer) CorrelateAlert(context.Context, *CorrelateAlertRequest) (*CorrelateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CorrelateAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetCorrelatedAlerts(context.Context, *GetCorrelatedAlertsRequest) (*GetCorrelatedAlertsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCorrelatedAlerts not implemented")
}
func (UnimplementedAlertManagementServiceServer) EnrichAlert(context.Context, *EnrichAlertRequest) (*EnrichAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetAlertContext(context.Context, *GetAlertContextRequest) (*GetAlertContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertContext not implemented")
}
func (UnimplementedAlertManagementServiceServer) DetectBurst(context.Context, *DetectBurstRequest) (*DetectBurstResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectBurst not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetBurstMetrics(context.Context, *GetBurstMetricsRequest) (*GetBurstMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBurstMetrics not implemented")
}
func (UnimplementedAlertManagementServiceServer) AcknowledgeAlert(context.Context, *AcknowledgeAlertRequest) (*AcknowledgeAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) ResolveAlert(context.Context, *ResolveAlertRequest) (*ResolveAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) EscalateAlert(context.Context, *EscalateAlertRequest) (*EscalateAlertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EscalateAlert not implemented")
}
func (UnimplementedAlertManagementServiceServer) ApplyFloodgate(context.Context, *ApplyFloodgateRequest) (*ApplyFloodgateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyFloodgate not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetSuppressionRules(context.Context, *GetSuppressionRulesRequest) (*GetSuppressionRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSuppressionRules not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetAlertMetrics(context.Context, *GetAlertMetricsRequest) (*GetAlertMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertMetrics not implemented")
}
func (UnimplementedAlertManagementServiceServer) GetAlertTrends(context.Context, *GetAlertTrendsRequest) (*GetAlertTrendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertTrends not implemented")
}
func (UnimplementedAlertManagementServiceServer) mustEmbedUnimplementedAlertManagementServiceServer() {
}
func (UnimplementedAlertManagementServiceServer) testEmbeddedByValue() {}

// UnsafeAlertManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertManagementServiceServer will
// result in compilation errors.
type UnsafeAlertManagementServiceServer interface {
	mustEmbedUnimplementedAlertManagementServiceServer()
}

func RegisterAlertManagementServiceServer(s grpc.ServiceRegistrar, srv AlertManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedAlertManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertManagementService_ServiceDesc, srv)
}

func _AlertManagementService_CreateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).CreateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_CreateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).CreateAlert(ctx, req.(*CreateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetAlert(ctx, req.(*GetAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_UpdateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).UpdateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_UpdateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).UpdateAlert(ctx, req.(*UpdateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_DeleteAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).DeleteAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_DeleteAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).DeleteAlert(ctx, req.(*DeleteAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_ListAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).ListAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_ListAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).ListAlerts(ctx, req.(*ListAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_SearchAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).SearchAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_SearchAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).SearchAlerts(ctx, req.(*SearchAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_CorrelateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CorrelateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).CorrelateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_CorrelateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).CorrelateAlert(ctx, req.(*CorrelateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetCorrelatedAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorrelatedAlertsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetCorrelatedAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetCorrelatedAlerts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetCorrelatedAlerts(ctx, req.(*GetCorrelatedAlertsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_EnrichAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).EnrichAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_EnrichAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).EnrichAlert(ctx, req.(*EnrichAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetAlertContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetAlertContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetAlertContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetAlertContext(ctx, req.(*GetAlertContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_DetectBurst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectBurstRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).DetectBurst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_DetectBurst_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).DetectBurst(ctx, req.(*DetectBurstRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetBurstMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBurstMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetBurstMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetBurstMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetBurstMetrics(ctx, req.(*GetBurstMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_AcknowledgeAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).AcknowledgeAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_AcknowledgeAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).AcknowledgeAlert(ctx, req.(*AcknowledgeAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_ResolveAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).ResolveAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_ResolveAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).ResolveAlert(ctx, req.(*ResolveAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_EscalateAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EscalateAlertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).EscalateAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_EscalateAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).EscalateAlert(ctx, req.(*EscalateAlertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_ApplyFloodgate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyFloodgateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).ApplyFloodgate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_ApplyFloodgate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).ApplyFloodgate(ctx, req.(*ApplyFloodgateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetSuppressionRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSuppressionRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetSuppressionRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetSuppressionRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetSuppressionRules(ctx, req.(*GetSuppressionRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetAlertMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetAlertMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetAlertMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetAlertMetrics(ctx, req.(*GetAlertMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlertManagementService_GetAlertTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertManagementServiceServer).GetAlertTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertManagementService_GetAlertTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertManagementServiceServer).GetAlertTrends(ctx, req.(*GetAlertTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertManagementService_ServiceDesc is the grpc.ServiceDesc for AlertManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "alert_management.AlertManagementService",
	HandlerType: (*AlertManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlert",
			Handler:    _AlertManagementService_CreateAlert_Handler,
		},
		{
			MethodName: "GetAlert",
			Handler:    _AlertManagementService_GetAlert_Handler,
		},
		{
			MethodName: "UpdateAlert",
			Handler:    _AlertManagementService_UpdateAlert_Handler,
		},
		{
			MethodName: "DeleteAlert",
			Handler:    _AlertManagementService_DeleteAlert_Handler,
		},
		{
			MethodName: "ListAlerts",
			Handler:    _AlertManagementService_ListAlerts_Handler,
		},
		{
			MethodName: "SearchAlerts",
			Handler:    _AlertManagementService_SearchAlerts_Handler,
		},
		{
			MethodName: "CorrelateAlert",
			Handler:    _AlertManagementService_CorrelateAlert_Handler,
		},
		{
			MethodName: "GetCorrelatedAlerts",
			Handler:    _AlertManagementService_GetCorrelatedAlerts_Handler,
		},
		{
			MethodName: "EnrichAlert",
			Handler:    _AlertManagementService_EnrichAlert_Handler,
		},
		{
			MethodName: "GetAlertContext",
			Handler:    _AlertManagementService_GetAlertContext_Handler,
		},
		{
			MethodName: "DetectBurst",
			Handler:    _AlertManagementService_DetectBurst_Handler,
		},
		{
			MethodName: "GetBurstMetrics",
			Handler:    _AlertManagementService_GetBurstMetrics_Handler,
		},
		{
			MethodName: "AcknowledgeAlert",
			Handler:    _AlertManagementService_AcknowledgeAlert_Handler,
		},
		{
			MethodName: "ResolveAlert",
			Handler:    _AlertManagementService_ResolveAlert_Handler,
		},
		{
			MethodName: "EscalateAlert",
			Handler:    _AlertManagementService_EscalateAlert_Handler,
		},
		{
			MethodName: "ApplyFloodgate",
			Handler:    _AlertManagementService_ApplyFloodgate_Handler,
		},
		{
			MethodName: "GetSuppressionRules",
			Handler:    _AlertManagementService_GetSuppressionRules_Handler,
		},
		{
			MethodName: "GetAlertMetrics",
			Handler:    _AlertManagementService_GetAlertMetrics_Handler,
		},
		{
			MethodName: "GetAlertTrends",
			Handler:    _AlertManagementService_GetAlertTrends_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/alert_management/alert_management_service.proto",
}
